const mongoose = require('mongoose');

/**
 * Application Schema
 * Tracks job applications created manually or generated by the multi-agent tailoring pipeline.
 */
const applicationSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'User ID is required'],
      index: true,
    },
    company: {
      type: String,
      required: [true, 'Company name is required'],
      trim: true,
    },
    roleTitle: {
      type: String,
      required: [true, 'Role title is required'],
      trim: true,
    },
    status: {
      type: String,
      enum: {
        values: ['wishlist', 'applied', 'interviewing', 'offer', 'rejected'],
        message: '{VALUE} is not a valid application status',
      },
      default: 'applied',
      index: true,
    },
    resumeId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Resume',
      default: null,
      index: true,
    },
    jdId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'JobDescription',
      default: null,
      index: true,
    },
    // Reference to the multi-agent pipeline run that created or tailored this application
    pipelineRunId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'PipelineRun',
      default: null,
      index: true,
    },
    runId: {
      type: String,
      default: null,
      trim: true,
      index: true,
    },
    appliedDate: {
      type: Date,
      default: Date.now,
    },
    notes: {
      type: String,
      default: '',
      trim: true,
    },
    tailoredBullets: {
      type: [mongoose.Schema.Types.Mixed],
      default: [],
    },
    coverLetter: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },
    fitScore: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },
  },
  {
    timestamps: true,
  }
);

// Compound index for user query performance
applicationSchema.index({ userId: 1, createdAt: -1 });

// Transform JSON output
applicationSchema.methods.toJSON = function () {
  const app = this.toObject();
  app.id = app._id;
  delete app.__v;
  return app;
};

const Application = mongoose.model('Application', applicationSchema);

module.exports = Application;
